// Projects configuration
const projectsConfig = {
    personal: [],
    commercial: [
        {
            id: 'dark-lord',
            icon: '💼',
            image: 'projects/commercial/dark-lord/cover.jpg',
            title: {
                ru: 'Dark Lord',
                en: 'Dark Lord'
            },
            tags: ['2D', 'PC', 'Card Game', 'Novel'],
            detailedDescription: {
                ru: "<div class=\"project-meta\"><p><strong>Роль:</strong> Unity-разработчик (в команде)</p><p><strong>Платформа:</strong> PC</p><p><strong>Технологии:</strong> Unity UI, DOTween, Spine, Yarn Spinner, Addressables, Unity Gaming Services, Steam SDK, Xsolla SDK, MVC, Git</p></div><h4>Описание:</h4><p>2D игра студии UndeadFox, сочетающая элементы нескольких жанров.</p><p>Мой первый полноценный коммерческий проект, ставший отправной точкой в карьере разработчика игр.</p><p>Работая в составе команды, прошёл весь цикл разработки — от создания MVP до релизной версии.</p><p>За время проекта вырос с уровня trainee до middle, получив обширный практический опыт в разработке игр на Unity.</p><h4>Мои задачи:</h4><ul class=\"tasks-list\"><li><span>Создание пользовательских интерфейсов с использованием Unity UI (в большом количестве)</span></li><li><span>Реализация разнообразных игровых механик по ТЗ</span></li><li><span>Интеграция анимаций с использованием DOTween и встроенных инструментов Unity (Animation, Animator)</span></li><li><span>Интеграция Spine-анимаций</span></li><li><span>Управление загружаемым контентом с помощью Addressables</span></li><li><span>Использование ScriptableObject для конфигурирования игровых данных</span></li><li><span>Реализация механик визуальной новеллы с использованием Yarn Spinner</span></li><li><span>Интеграция игровых сервисов и платформ (Unity Gaming Services, Steam, Xsolla)</span></li><li><span>Асинхронное программирование (async/await, корутины)</span></li><li><span>Применение шаблонов проектирования (Синглтон, Сервис-локатор, Фабричный метод, Адаптер, Фасад, Обсервер, Медиатор, Стратегия)</span></li><li><span>Отладка и исправление ошибок</span></li><li><span>Сборка и загрузка билдов в Steam через Steamworks</span></li><li><span>Командная работа с использованием Git и архитектурного подхода MVC</span></li></ul>",
                en: "<div class=\"project-meta\"><p><strong>Role:</strong> Unity Developer (team member)</p><p><strong>Platform:</strong> PC</p><p><strong>Technologies:</strong> Unity UI, DOTween, Spine, Yarn Spinner, Addressables, Unity Gaming Services, Steam SDK, Xsolla SDK, MVC, Git</p></div><h4>Description:</h4><p>A 2D game by UndeadFox Studio that combines elements of multiple genres.</p><p>My first full-scale commercial project, which became the starting point of my career as a game developer.</p><p>As part of the team, I went through the entire development cycle — from creating the MVP to the release version.</p><p>During the project, I grew from a trainee to a middle developer, gaining extensive hands-on experience in Unity game development.</p><h4>My responsibilities:</h4><ul class=\"tasks-list\"><li><span>Creating user interfaces using Unity UI (in large quantity)</span></li><li><span>Implementing various gameplay mechanics based on technical specifications</span></li><li><span>Integrating animations using DOTween and Unity's built-in tools (Animation, Animator)</span></li><li><span>Integrating Spine animations</span></li><li><span>Managing downloadable content via Addressables</span></li><li><span>Using ScriptableObject to configure game data</span></li><li><span>Implementing visual novel mechanics with Yarn Spinner</span></li><li><span>Integrating game services and platforms (Unity Gaming Services, Steam, Xsolla)</span></li><li><span>Asynchronous programming (async/await, coroutines)</span></li><li><span>Applying design patterns (Singleton, Service Locator, Factory Method, Adapter, Facade, Observer, Mediator, Strategy)</span></li><li><span>Debugging and fixing issues</span></li><li><span>Building and uploading builds to Steam via Steamworks</span></li><li><span>Collaborating with the team using Git and the MVC architectural approach</span></li></ul>"
            },
            links: [
                { text: { ru: 'Steam', en: 'Steam' }, url: 'https://store.steampowered.com/app/2515030/Dark_Lord/' }
            ]
        }
    ]
};